baseURL = "https://lisp.netlify.app"
languageCode = "en-us"
title = "Hiroshima.lisp"
enableEmoji = true
enableInlineShortcodes = true
enableGitInfo = true
hasCJKLanguage = true
googleAnalytics = "UA-165099679-2"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

## Social links
[[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://de.linkedin.com/"

[[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/lxndrblz/anatole/"

[[params.socialIcons]]
  icon = "fa-instagram"
  title = "instagram"
  url = "https://www.instagram.com/"

[[params.socialIcons]]
  icon = "fa-envelope"
  title = "e-mail"
  url = "mailto:mail@alexbilz.com"

[params.math]
  global = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
  engine = "katex"  # options: "katex", "mathjax". default is "mathjax".

[params]
  homeText = "You just made a Hugo blog from scratch."
  Copyright = "CC0"

[taxonomies]
  tag = "tags"
