languageCode = "ja-jp"
enableEmoji = true
enableInlineShortcodes = true
enableGitInfo = true
hasCJKLanguage = true
googleAnalytics = "UA-888888888-8"

[params]
  author = "ac1965"
  Copyright = "Powered by Hugo. Copyright @ 2009 - 2020 YAMASHITA Takao."
  description = "The sound, old pond and frog jump into water."

## Social links
[[params.socialIcons]]
  icon = "fa-github"
  url = "https://github.com/ac1965"

[[params.socialIcons]]
  icon = "fa-twitter"
  url = "https://twitter.com/ac1965"

[params.math]
  global = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
  engine = "katex"  # options: "katex", "mathjax". default is "mathjax".

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
